### ISSUE TITLE
fatal error: THC/THC.h: No such file or directory

### ISSUE THREAD

**Issue by sijieaaa** [dvlab-research/SparseTransformer#2]
Hi Yukang,

![Screenshot from 2023-03-29 14-39-19](https://user-images.githubusercontent.com/58644619/228447423-28339ea3-a641-4d75-a837-caf0869bc835.png)

Thanks for your pioneering work!
However, there is a potential bug.
As <THC/THC.h> is not supported since pytorch>1.11, the installation would fail.
You can replace <THC/THC.h> with <ATen/ATen.h> in all possible places.
By doing so, sptr can be successfully installed. (For pytorch2.0, it also works.)

For example:
https://github.com/dvlab-research/SparseTransformer/blob/0ac6f1ceb7effaa82c3dc1b945564d80c1cc55a8/src/sptr/attention/attention_cuda.cpp#L2

Replace <THC/THC.h> with <ATen/ATen.h>

Thanks.

**Comment by X-Lai** [comment]
Thanks for your advice. We have already fixed it.
